### PR TITLE
[wip] Update config.json

### PR DESCRIPTION
**Pull request by MikaXII**
Change port number to resolv conflict with https://github.com/MikaXII/recalbox-webconfig (a link added in webconfig to this project)

### CODE REVIEW

**Comment by MikaXII** [comment]
Attendre la confirmation de digital sur le choix du port pls :)

**Comment by digitalLumberjack** [comment]
Isn't it configurable with a parameter when we start the server ?

**Comment by miroof** [comment]
Hello Mika and Digit,

You can use the file config.json in order to set the port ;)

Miroof

Le lun. 24 août 2015 19:35, digitalLumberjack <notifications@github.com> a
écrit :

**Comment by digitalLumberjack** [comment]
Haha it's already a config file. Mika... :P

**Pull request closed without merging**
