### PR TITLE
[WIP] Fix my previous PR

### PR DESCRIPTION
**Pull request by MikaXII**

### CODE REVIEW

**Comment by MikaXII** [comment]
I didn't see main.coffee...

**Comment by roba91** [comment]
Try something like this:

```coffeescript
port = process.env.PORT || config.port

http.on 'error', (err) ->
  switch err.message
    when "listen EACCES"
      console.error "You don't have permissions to open port", port,
        "For ports smaller than 1024, you need root privileges."
  throw err

http.listen port, () ->
    console.info "Listening on #{port}"
```

  * it also logs the right port on EACCES
  * it's easier to read

**Comment by MikaXII** [comment]
This is why I don't merge yesterday, I was tired.

**Comment by roba91** [comment]
Nice. You missed to change the line
```coffeescript
    console.error "You don't have permissions to open port", config.port,
```
to
```coffeescript
    console.error "You don't have permissions to open port", port,
```

**Pull request merged**
